version: '3'
services: 
    router:
        build: ./Docker
        container_name: router
        privileged: true
        tty: true
        volumes: 
            - ./:/root/go/src/github.com/spectrex02/router-shakyo-go

    # host:
    #     build: ./Docker/centos
    #     container_name: host
    #     # privileged: true
    #     tty: true

